CREATE TABLE DEPARTMENTS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    DEPARTMENT_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE DESIGNATIONS (
    ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    DESIGNATIONS VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE EMPLOYEES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ID_CARD_NO VARCHAR(50),
    NAME VARCHAR(75) NOT NULL,
    DEPARTMENT_ID UUID REFERENCES DEPARTMENTS(ID) ON DELETE RESTRICT,
    DESIGNATION_ID UUID REFERENCES DESIGNATIONS(ID) ON DELETE RESTRICT,
    PHONE_NO VARCHAR(20),
    EMAIL VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

alter table EMPLOYEES add column company_id uuid references company (id) on delete restrict;

CREATE TABLE ATTENDANCE_RECORD (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EMPLOYEE_ID UUID REFERENCES EMPLOYEES(ID) ON DELETE RESTRICT,
    LATITUDE DOUBLE PRECISION NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    SELFIE_URL TEXT NOT NULL,
    SUBMITTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS BOOLEAN DEFAULT FALSE
);

CREATE TABLE COMPANY (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE OFFICES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR(100) NOT NULL,
    COMPANY_ID UUID REFERENCES COMPANY (ID)
);

create table office_locations (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    address text,
    LATITUDE DOUBLE PRECISION NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    office_id uuid references offices(id)
);

select * from ATTENDANCE_RECORD;